apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-saqlainmustaq-com
  namespace: default
spec:
  secretName: local-saqlainmushtaq-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.saqlainmushtaq.com"
  dnsNames:
    - "*.saqlainmushtaq.com"